<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>RayoCrossPlatformApp.Desktop</RootNamespace>
    <AssemblyName>RayoCrossPlatformApp.Desktop</AssemblyName>
    <ApplicationIcon>..\RayoCrossPlatformApp\Assets\AppIcon\AppIcon.ico</ApplicationIcon>
    <RayoVersion>0.1.10</RayoVersion>
    <HotReloadEnabled Condition="'$(Configuration)' == 'Debug'">true</HotReloadEnabled>
    <HotReloadSupported Condition="'$(Configuration)' == 'Debug'">true</HotReloadSupported>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RayoCrossPlatformApp\RayoCrossPlatformApp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Rayo.Hosting.Desktop" Version="0.1.14" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\RayoCrossPlatformApp\Assets\AppIcon\AppIcon.png" Link="Assets\AppIcon\AppIcon.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
