<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>
    <RootNamespace>RayoDesktopApp</RootNamespace>
    <AssemblyName>RayoDesktopApp</AssemblyName>
    <ApplicationIcon>Assets\AppIcon\AppIcon.ico</ApplicationIcon>
    <RayoVersion>0.1.10</RayoVersion>
    <SourceGeneratorNamespace>$(RootNamespace).Extensions</SourceGeneratorNamespace>
    <HotReloadEnabled Condition="'$(Configuration)' == 'Debug'">true</HotReloadEnabled>
    <HotReloadSupported Condition="'$(Configuration)' == 'Debug'">true</HotReloadSupported>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Rayo" Version="0.1.14" />
    <PackageReference Include="Rayo.Hosting.Desktop" Version="0.1.14" />
    <PackageReference Include="Rayo.FluentApiGenerator" Version="0.1.14" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <CompilerVisibleProperty Include="RootNamespace" />
    <CompilerVisibleProperty Include="SourceGeneratorNamespace" />
    <Compile Remove="Generated\**" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\AppIcon\AppIcon.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
